version: '3'
services:
  # web:
  #   build: ./app
  #   command: npm run start
  #   ports:
  #     - "3000:3000"
  #   depends_on:
  #     - mongo
  #   links:
  #     - mongo
  # server:
  #   build: ./server
  #   command: npm run start
  #   ports:
  #     - "8080:8080"
  #   depends_on:
  #     - mongo
  #   links:
  #     - mongo
  mongo:
    image: mongo:latest
    ports: 
      - "27017:27017"